# Generated by Django 5.0.14 on 2026-06-30 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('event_type', models.CharField(choices=[('BIRTHDAY', 'Anniversaire'), ('WEDDING', 'Mariage / Fiançailles'), ('CORPORATE', "Événement d'entreprise"), ('PRIVATE_CHEF', 'Chef Privé à domicile'), ('BUFFET', 'Service Buffet'), ('COCKTAIL', 'Service Cocktail'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('event_date', models.DateField()),
                ('guest_count', models.PositiveIntegerField()),
                ('notes', models.TextField(verbose_name='Détails du projet / demandes particulières')),
                ('status', models.CharField(choices=[('PENDING', 'Demande en attente'), ('SENT', 'Devis envoyé'), ('COMPLETED', 'Événement validé / effectué'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de devis événementiel',
                'verbose_name_plural': 'Demandes de devis événementiels',
                'ordering': ['-created_at'],
            },
        ),
    ]
