[program:gunicorn]
command=gunicorn kay_mama.wsgi:application --bind 0.0.0.0:8000 --workers 3
directory=/app
user=nobody
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/gunicorn.log

[program:celery]
command=celery -A kay_mama worker -l info
directory=/app
user=nobody
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/celery.log
