# Generated by Django 5.0.14 on 2026-06-30 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('delivery_method', models.CharField(choices=[('PICKUP', 'À emporter (sur place)'), ('DELIVERY', 'Livraison à domicile')], default='PICKUP', max_length=20)),
                ('delivery_address', models.TextField(blank=True)),
                ('delivery_time', models.DateTimeField()),
                ('special_instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('INCOMING', 'Reçue / En attente'), ('PREPARING', 'En préparation'), ('READY', 'Prête'), ('DELIVERED', 'En livraison'), ('COMPLETED', 'Terminée'), ('CANCELLED', 'Annulée')], default='INCOMING', max_length=20)),
                ('payment_status', models.CharField(choices=[('PENDING', 'En attente'), ('PAID', 'Payé'), ('FAILED', 'Échoué')], default='PENDING', max_length=20)),
                ('payment_method', models.CharField(choices=[('CARD', 'Carte bancaire en ligne'), ('CASH', 'Espèces au comptoir'), ('ON_DELIVERY', 'À la livraison')], default='CARD', max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.dish')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.dishvariant')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
            },
        ),
    ]
