# Generated by Django 5.0.14 on 2026-06-30 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('date', models.DateField()),
                ('time_slot', models.TimeField()),
                ('guest_count', models.PositiveIntegerField()),
                ('occasion', models.CharField(choices=[('BIRTHDAY', 'Anniversaire'), ('WEDDING', 'Mariage / Fiançailles'), ('BUSINESS', "Repas d'affaires"), ('FAMILY', 'Fête de famille'), ('OTHER', 'Autre événement')], default='OTHER', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'En attente'), ('APPROVED', 'Confirmée'), ('REJECTED', 'Refusée'), ('MODIFIED', 'Modifiée')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date', '-time_slot'],
            },
        ),
    ]
