# Generated by Django 5.0.14 on 2026-07-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='occasion',
            field=models.CharField(choices=[('BIRTHDAY', 'Anniversaire'), ('WEDDING', 'Mariage / Fiançailles'), ('BUSINESS', "Repas d'affaires"), ('FAMILY', 'Fête de famille'), ('SALON', 'Salon de Beauté'), ('OTHER', 'Autre événement')], default='OTHER', max_length=20),
        ),
    ]
