# Generated by Django 5.0.14 on 2026-06-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Date bloquée',
                'verbose_name_plural': 'Dates bloquées',
            },
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], unique=True)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('is_closed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': "Horaire d'ouverture",
                'verbose_name_plural': "Horaires d'ouverture",
                'ordering': ['day_of_week'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Kay Mama Cuisine Créole', max_length=100)),
                ('address', models.TextField(default='48 Av. François Ronjon, 97300 Cayenne')),
                ('phone', models.CharField(default='694 08 12 80', max_length=20)),
                ('whatsapp', models.CharField(default='+594694081280', max_length=20)),
                ('facebook', models.CharField(default='Kay Mama Cuisine Créole', max_length=100)),
                ('google_maps_url', models.TextField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3976.223841071489!2d-52.32789182390141!3d4.935747439972338!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8d12163b7ad781ff%3A0xe543df5e967a1fd7!2s48%20Av.%20Fran%C3%A7ois%20Ronjon%2C%20Cayenne%2097300%2C%20French%20Guiana!5e0!3m2!1sen!2s!4v1700000000000!5m2!1sen!2s')),
                ('max_guests_per_slot', models.PositiveIntegerField(default=30)),
                ('delivery_min_dishes', models.PositiveIntegerField(default=5)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('is_ordering_enabled', models.BooleanField(default=True)),
                ('is_reservations_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Paramètre du Restaurant',
                'verbose_name_plural': 'Paramètres du Restaurant',
            },
        ),
    ]
