# Generated by Django 5.0.14 on 2026-06-30 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(choices=[('HOME', "Page d'accueil"), ('ABOUT', 'À propos'), ('EVENTS', 'Événements'), ('CONTACT', 'Contact')], default='HOME', max_length=20)),
                ('section_key', models.CharField(help_text="Ex: 'hero_title', 'about_chef_description'", max_length=100, unique=True)),
                ('title', models.CharField(blank=True, max_length=250)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('button_text', models.CharField(blank=True, max_length=100)),
                ('button_link', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'verbose_name': 'Section de page',
                'verbose_name_plural': 'Sections de pages',
                'ordering': ['page', 'section_key'],
            },
        ),
        migrations.CreateModel(
            name='SEOPageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(help_text="Ex: '/', '/menu/', '/about/'", max_length=250, unique=True)),
                ('meta_title', models.CharField(blank=True, max_length=80)),
                ('meta_description', models.CharField(blank=True, max_length=160)),
                ('og_title', models.CharField(blank=True, max_length=80)),
                ('og_description', models.CharField(blank=True, max_length=160)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='seo/')),
            ],
            options={
                'verbose_name': 'Métadonnée SEO Page',
                'verbose_name_plural': 'Métadonnées SEO Pages',
            },
        ),
    ]
